pipeline {
    agent {
        docker {
            image 'maven:3-alpine' // Use a Maven image as an example
        }
    }
    stages {
        stage('Checkout') {
            steps {
                // Checkout your source code from version control (e.g., Git)
                checkout scm
            }
        }
        stage('Create HelloWorld.java') {
            steps {
                script {
                    writeFile file: 'src/main/java/HelloWorld.java', text: '''
                        public class HelloWorld {
                            public static void main(String[] args) {
                                System.out.println("Hello, World!");
                            }
                        }
                    '''
                }
            }
        }
        stage('Build') {
            steps {
                // Build your Java project using Maven
                sh 'mvn clean install'
            }
        }
    }
}
